/*
 * Consola.java
 *
 * Created on 4 de octubre de 2006, 12:59 AM
 */

/**
 *
 * @author  ApokalipsyS
 */
public class Consola extends javax.swing.JFrame {
    
    /** Creates new form Consola */
    public Consola() {
        initComponents();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        limpiar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("JSeudo Script Viewer");
        setAlwaysOnTop(true);
        console.setBackground(new java.awt.Color(0, 0, 0));
        console.setFont(new java.awt.Font("Arial", 0, 18));
        console.setForeground(new java.awt.Color(0, 204, 51));
        console.setDisabledTextColor(new java.awt.Color(0, 204, 0));
        console.setEnabled(false);
        console.setMinimumSize(new java.awt.Dimension(300, 300));
        console.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setViewportView(console);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Opciones");
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jMenu1.add(limpiar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
            console.setText("");
    }//GEN-LAST:event_limpiarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consola().setVisible(true);
            }
        });
    }
    
    public void setText(String texto)
    {
        console.setText(console.getText()+"\n"+texto);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane console;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem limpiar;
    // End of variables declaration//GEN-END:variables
    
}
